### ISSUE TITLE
Importing npm modules

### ISSUE THREAD

**Issue by CallumJHays** [MartinKavik/seed-quickstart-webpack#1]
HI! Really love what you have done here and the work you and David are bringing to the web as a whole. Is it possible to import and use (non-node) npm modules?

For example, I try adding 'react' to `package.json`:
```json
"dependencies": {
    "react": "^16.8.6"
}
```

importing react in `clock.ts`:
```javascript
import React from 'react';
```

But running `yarn build` results in a `ts-loader` error:
![image](https://user-images.githubusercontent.com/13251689/59659593-e2ccf080-91e9-11e9-9da3-7ad7ff27b46e.png)

I've had a google to see if similar problems were found with ts-loader but I couldn't figure it out. Had a brief scan over the webpack docs too but I'm not familiar with webpack.

Help? :smile_cat:

**Comment by CallumJHays** [comment]
Also, compiling `clock.ts` to js with `tsc` works and my typescript server in vscode doesn't raise any module resolution errors

**Comment by MartinKavik** [comment]
Hi and thanks!

You have 2 options how to resolve it:

1. There is this error in your screen: `TS6133: 'React' is declared but its value is never read.` - so just use React somehow, e.g.:
```typescript
// clock.ts
import * as React from "react";

console.log(`React version: ${React.version}`);
```

2. I like strict linters, if you don't like it, just turn it off:
```js
// /configs/tsconfig.base.json

{
  "compilerOptions": {
    "target": "es5",
    "module": "esNext",
    "lib": ["dom", "es2015"],
    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "noImplicitAny": true,
    // "noUnusedLocals": true,
    ...
```

And for the second problem: `TS2307: Cannot find module 'react'`:
1. Shutdown dev-server if running
2. `yarn` or `yarn install`

I was testing it with `"react": "^16.8.6"` in `dependencies` and `"@types/react": "^16.8.20"` in `devDependencies` in `/package.json`.

--- 

P.S. I want to use this quickstart for a new Seed homepage or at least my web so there will be probably some updates and changes in the future.

**Comment by MartinKavik** [comment]
@CallumJHays If it resolved your problems and you don't have other questions, close the issue, please :)

**Comment by CallumJHays** [comment]
Thanks @MartinKavik, I think this was one of those weird cases of "it wouldn't work until I complained about it" :'P

**Comment by CallumJHays** [comment]
Hey @MartinKavik , do you know why importing a module like `react` works fine,
whereas importing a module like `[https://github.com/MaxGfeller/youtube-search](npm/youtube-search)` fails to resolve the module in any wasm-bindgen'ed file?

**Comment by CallumJHays** [comment]
Actually I found a solution!

adding `"compilerOptions": { "moduleResolution": "node" }` to `config/tsconfig.base.json` fixed the module resolution errors I was experiencing in some cases

**Comment by MartinKavik** [comment]
Nice! I'll add it into `readme` while I will be refactoring quickstart.
